person(andrew). 
person(bernard).  
person(cathleen).  
person(daphne).
person(edith).  
person(fred).  
person(george).  
person(john).
person(louis).  
person(oscar).  
person(paul).  
person(robert).
person(stephen).  
person(sylvia).  
person(william). 
person(ada).
father(william,sylvia).
father(oscar,louis).
father(oscar,daphne).
father(oscar,cathleen).
father(oscar,fred).
father(oscar,bernard).
father(louis,stephen).
father(louis,andrew).
father(louis,robert).
father(louis,john).
father(george,oscar).
father(paul,edith).
mother(sylvia,stephen).
mother(sylvia,andrew).
mother(sylvia,robert).
mother(sylvia,john).
mother(edith,louis).
mother(edith,daphne).
mother(edith,cathleen).
mother(edith,fred).
mother(edith,bernard).
mother(ada,sylvia).
