pos(parent(ada,sylvia)).
pos(parent(edith,bernard)).
pos(parent(edith,cathleen)).
pos(parent(edith,daphne)).
pos(parent(edith,fred)).
pos(parent(edith,louis)).
pos(parent(george,oscar)).
pos(parent(louis,andrew)).
pos(parent(louis,john)).
pos(parent(louis,robert)).
pos(parent(louis,stephen)).
pos(parent(oscar,bernard)).
pos(parent(oscar,cathleen)).
pos(parent(oscar,daphne)).
pos(parent(oscar,fred)).
pos(parent(oscar,louis)).
pos(parent(paul,edith)).
pos(parent(sylvia,andrew)).
pos(parent(sylvia,john)).
pos(parent(sylvia,robert)).
pos(parent(sylvia,stephen)).
pos(parent(william,sylvia)).
pos(grandfather(george,bernard)).
pos(grandfather(george,cathleen)).
pos(grandfather(george,daphne)).
pos(grandfather(george,fred)).
pos(grandfather(george,louis)).
pos(grandfather(oscar,andrew)).
pos(grandfather(oscar,john)).
pos(grandfather(oscar,robert)).
pos(grandfather(oscar,stephen)).
pos(grandfather(paul,bernard)).
pos(grandfather(paul,cathleen)).
pos(grandfather(paul,daphne)).
pos(grandfather(paul,fred)).
pos(grandfather(paul,louis)).
pos(grandfather(william,andrew)).
pos(grandfather(william,john)).
pos(grandfather(william,robert)).
pos(grandfather(william,stephen)).
pos(grandparent(ada,andrew)).
pos(grandparent(ada,john)).
pos(grandparent(ada,robert)).
pos(grandparent(ada,stephen)).
pos(grandparent(edith,andrew)).
pos(grandparent(edith,john)).
pos(grandparent(edith,robert)).
pos(grandparent(edith,stephen)).
pos(grandparent(george,bernard)).
pos(grandparent(george,cathleen)).
pos(grandparent(george,daphne)).
pos(grandparent(george,fred)).
pos(grandparent(george,louis)).
pos(grandparent(oscar,andrew)).
pos(grandparent(oscar,john)).
pos(grandparent(oscar,robert)).
pos(grandparent(oscar,stephen)).
pos(grandparent(paul,bernard)).
pos(grandparent(paul,cathleen)).
pos(grandparent(paul,daphne)).
pos(grandparent(paul,fred)).
pos(grandparent(paul,louis)).
pos(grandparent(william,andrew)).
pos(grandparent(william,john)).
pos(grandparent(william,robert)).
pos(grandparent(william,stephen)).
neg(parent(ada,andrew)).
neg(parent(ada,john)).
neg(parent(ada,robert)).
neg(parent(ada,stephen)).
neg(parent(edith,andrew)).
neg(parent(edith,john)).
neg(parent(edith,robert)).
neg(parent(edith,stephen)).
neg(parent(george,bernard)).
neg(parent(george,cathleen)).
neg(parent(george,daphne)).
neg(parent(george,fred)).
neg(parent(george,louis)).
neg(parent(oscar,andrew)).
neg(parent(oscar,john)).
neg(parent(oscar,robert)).
neg(parent(oscar,stephen)).
neg(parent(paul,bernard)).
neg(parent(paul,cathleen)).
neg(parent(paul,daphne)).
neg(parent(paul,fred)).
neg(parent(paul,louis)).
neg(parent(william,andrew)).
neg(parent(william,john)).
neg(parent(william,robert)).
neg(parent(william,stephen)).
neg(parent(sylvia,ada)).
neg(parent(bernard,edith)).
neg(parent(cathleen,edith)).
neg(parent(daphne,edith)).
neg(parent(fred,edith)).
neg(parent(louis,edith)).
neg(parent(oscar,george)).
neg(parent(andrew,louis)).
neg(parent(john,louis)).
neg(parent(robert,louis)).
neg(parent(stephen,louis)).
neg(parent(bernard,oscar)).
neg(parent(cathleen,oscar)).
neg(parent(daphne,oscar)).
neg(parent(fred,oscar)).
neg(parent(louis,oscar)).
neg(parent(edith,paul)).
neg(parent(andrew,sylvia)).
neg(parent(john,sylvia)).
neg(parent(robert,sylvia)).
neg(parent(stephen,sylvia)).
neg(parent(sylvia,william)).
neg(grandparent(ada,sylvia)).
neg(grandparent(edith,bernard)).
neg(grandparent(edith,cathleen)).
neg(grandparent(edith,daphne)).
neg(grandparent(edith,fred)).
neg(grandparent(edith,louis)).
neg(grandparent(george,oscar)).
neg(grandparent(louis,andrew)).
neg(grandparent(louis,john)).
neg(grandparent(louis,robert)).
neg(grandparent(louis,stephen)).
neg(grandparent(oscar,bernard)).
neg(grandparent(oscar,cathleen)).
neg(grandparent(oscar,daphne)).
neg(grandparent(oscar,fred)).
neg(grandparent(oscar,louis)).
neg(grandparent(paul,edith)).
neg(grandparent(sylvia,andrew)).
neg(grandparent(sylvia,john)).
neg(grandparent(sylvia,robert)).
neg(grandparent(sylvia,stephen)).
neg(grandparent(william,sylvia)).
neg(grandfather(ada,sylvia)).
neg(grandfather(edith,bernard)).
neg(grandfather(edith,cathleen)).
neg(grandfather(edith,daphne)).
neg(grandfather(edith,fred)).
neg(grandfather(edith,louis)).
neg(grandfather(george,oscar)).
neg(grandfather(louis,andrew)).
neg(grandfather(louis,john)).
neg(grandfather(louis,robert)).
neg(grandfather(louis,stephen)).
neg(grandfather(oscar,bernard)).
neg(grandfather(oscar,cathleen)).
neg(grandfather(oscar,daphne)).
neg(grandfather(oscar,fred)).
neg(grandfather(oscar,louis)).
neg(grandfather(paul,edith)).
neg(grandfather(sylvia,andrew)).
neg(grandfather(sylvia,john)).
neg(grandfather(sylvia,robert)).
neg(grandfather(sylvia,stephen)).
neg(grandfather(william,sylvia)).
neg(grandfather(ada,andrew)).
neg(grandfather(ada,john)).
neg(grandfather(ada,robert)).
neg(grandfather(ada,stephen)).
neg(grandfather(edith,andrew)).
neg(grandfather(edith,john)).
neg(grandfather(edith,robert)).
neg(grandfather(edith,stephen)).
